apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: app
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: node:18-alpine
        ports:
        - containerPort: 3000
        command:
        - "node"
        - "-e"
        - |
          const http = require('http');
          const server = http.createServer((req, res) => {
            res.writeHead(200, {'Content-Type': 'application/json'});
            res.end(JSON.stringify({ status: 'ok', message: 'Backend is running', db: 'mysql' }));
          });
          server.listen(3000, () => console.log('Backend running on 3000'));
        env:
        - name: DB_HOST
          value: "mysql"
        - name: DB_PORT
          value: "3306"