apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: app
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: frontend-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: app
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>3-Tier App</title></head>
    <body style="font-family: Arial; text-align: center; margin-top: 100px;">
      <h1>Frontend</h1>
      <p>Calling backend...</p>
      <script>
        fetch('http://' + window.location.hostname + ':30081/health')
          .then(res => res.json())
          .then(data => document.querySelector('p').textContent = 'Backend says: ' + JSON.stringify(data))
          .catch(err => document.querySelector('p').textContent = 'Backend unreachable: ' + err);
      </script>
    </body>
    </html>